### PR TITLE
Add code/test upload modal

### PR DESCRIPTION
**Pull request by SuNaden**

### CODE REVIEW

**Comment by martinzlocha** [comment]
Missing a submit button, also there needs to be one more slot to upload the expected output file.

image

**Comment by mishrabhinav** [comment]
screen shot 2017-11-28 at 23 16 27

**Comment by mishrabhinav** [comment]
I have something like this ready and currently working on the frontend. We should have the ability to create new templates relatively soon. Do you want to continue with your modal instead @SuNaden? What do you think @martinzlocha?

**Comment by SuNaden** [comment]
@martinzlocha interesting mine looks completely different and I swear that I pushed also the submit button :D I would not continue, @mishrabhinav has got it already working

**Pull request closed without merging**
